"""payments and assistance requests table

Revision ID: 7a4b7d2af8bc
Revises: 25e5e64df30f
Create Date: 2024-07-30 14:27:58.329084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4b7d2af8bc'
down_revision = '25e5e64df30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.Enum('low', 'medium', 'high'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], name=op.f('fk_assistance_requests_mechanic_id_mechanics')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_assistance_requests_payment_id_payments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assistance_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('credit_card', 'paypal', 'bank_transfer'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed'), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['assistance_requests.id'], name=op.f('fk_payments_request_id_assistance_requests')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('assistance_requests')
    # ### end Alembic commands ###
